openapi: 3.1.0
info:
  title: ""
  version: ""
paths:
  /v1/neuralNetwork/create:
    post:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNeuralNetworkRequest'
        required: true
      responses:
        "200":
          description: neuralNetwork.NeuralNetwork.Create response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateNeuralNetworkResponse'
  /v1/neuralNetwork/list:
    get:
      operationId: list
      parameters:
        - name: state.activationFunction
          in: query
          schema:
            $ref: '#/components/schemas/TrainingState.ActivationFunctionEnum'
        - name: state.createdAt
          in: query
          schema:
            type: string
            format: date-time
        - name: state.currentEpoch
          in: query
          schema:
            type: integer
            format: int32
        - name: state.epochBatch
          in: query
          schema:
            type: integer
            format: int32
        - name: state.epochs
          in: query
          schema:
            type: integer
            format: int32
        - name: state.learningRate
          in: query
          schema:
            type: number
            format: float
        - name: state.numInputs
          in: query
          schema:
            type: integer
            format: int32
        - name: state.numLayers
          in: query
          schema:
            type: integer
            format: int32
        - name: state.numOutputs
          in: query
          schema:
            type: integer
            format: int32
        - name: state.regularization
          in: query
          schema:
            $ref: '#/components/schemas/TrainingState.RegularizationEnum'
        - name: state.regularizationRate
          in: query
          schema:
            type: number
            format: float
        - name: state.state
          in: query
          schema:
            $ref: '#/components/schemas/TrainingState.TrainingStateEnum'
        - name: state.testLoss
          in: query
          schema:
            type: number
            format: float
        - name: state.trainingLoss
          in: query
          schema:
            type: number
            format: float
        - name: state.trainingType
          in: query
          schema:
            $ref: '#/components/schemas/TrainingState.TrainingTypeEnum'
        - name: state.updatedAt
          in: query
          schema:
            type: string
            format: date-time
        - name: state.uuid
          in: query
          schema:
            type: string
      responses:
        "200":
          description: neuralNetwork.NeuralNetwork.List response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNeuralNetworkResponse'
  /v1/neuralNetwork/load:
    post:
      operationId: load
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoadNeuralNetworkRequest'
        required: true
      responses:
        "200":
          description: neuralNetwork.NeuralNetwork.Load response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoadNeuralNetworkResponse'
  /v1/neuralNetwork/ping:
    get:
      operationId: ping
      responses:
        "200":
          description: neuralNetwork.NeuralNetwork.Ping response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingNeuralNetworkResponse'
  /v1/neuralNetwork/save:
    post:
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveNeuralNetworkRequest'
        required: true
      responses:
        "200":
          description: neuralNetwork.NeuralNetwork.Save response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveNeuralNetworkResponse'
  /v1/neuralNetwork/testStream:
    post:
      operationId: testStream
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestStreamNeuralNetworkRequest'
        required: true
      responses:
        "200":
          description: neuralNetwork.NeuralNetwork.TestStream response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestStreamNeuralNetworkResponse'
  /v1/neuralNetwork/train:
    get:
      operationId: train
      parameters:
        - name: state.activationFunction
          in: query
          schema:
            $ref: '#/components/schemas/TrainingState.ActivationFunctionEnum'
        - name: state.createdAt
          in: query
          schema:
            type: string
            format: date-time
        - name: state.currentEpoch
          in: query
          schema:
            type: integer
            format: int32
        - name: state.epochBatch
          in: query
          schema:
            type: integer
            format: int32
        - name: state.epochs
          in: query
          schema:
            type: integer
            format: int32
        - name: state.learningRate
          in: query
          schema:
            type: number
            format: float
        - name: state.numInputs
          in: query
          schema:
            type: integer
            format: int32
        - name: state.numLayers
          in: query
          schema:
            type: integer
            format: int32
        - name: state.numOutputs
          in: query
          schema:
            type: integer
            format: int32
        - name: state.regularization
          in: query
          schema:
            $ref: '#/components/schemas/TrainingState.RegularizationEnum'
        - name: state.regularizationRate
          in: query
          schema:
            type: number
            format: float
        - name: state.state
          in: query
          schema:
            $ref: '#/components/schemas/TrainingState.TrainingStateEnum'
        - name: state.testLoss
          in: query
          schema:
            type: number
            format: float
        - name: state.trainingLoss
          in: query
          schema:
            type: number
            format: float
        - name: state.trainingType
          in: query
          schema:
            $ref: '#/components/schemas/TrainingState.TrainingTypeEnum'
        - name: state.updatedAt
          in: query
          schema:
            type: string
            format: date-time
        - name: state.uuid
          in: query
          schema:
            type: string
      responses:
        "200":
          description: neuralNetwork.NeuralNetwork.Train response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainNeuralNetworkResponse'
  /v1/neuralNetwork/update:
    post:
      operationId: test
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestNeuralNetworkRequest'
        required: true
      responses:
        "200":
          description: neuralNetwork.NeuralNetwork.Test response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestNeuralNetworkResponse'
components:
  schemas:
    CreateNeuralNetworkRequest:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    CreateNeuralNetworkResponse:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    ListNeuralNetworkResponse:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    LoadNeuralNetworkRequest:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    LoadNeuralNetworkResponse:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    PingNeuralNetworkResponse:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        description:
          type: string
        data:
          type: string
    SaveNeuralNetworkRequest:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    SaveNeuralNetworkResponse:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    TestNeuralNetworkRequest:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    TestNeuralNetworkResponse:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    TestStreamNeuralNetworkRequest:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
        action:
          $ref: '#/components/schemas/TrainingAction'
    TestStreamNeuralNetworkResponse:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    TrainNeuralNetworkResponse:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/TrainingState'
    TrainingAction:
      type: object
      properties:
        action:
          $ref: '#/components/schemas/TrainingAction.TrainingActionEnum'
    TrainingAction.TrainingActionEnum:
      type: string
      enum:
        - TrainingActionIgnore
        - Start
        - Pause
        - Stop
    TrainingState:
      type: object
      properties:
        uuid:
          type: string
        learningRate:
          type: number
          format: float
        epochs:
          type: integer
          format: int32
        epochBatch:
          type: integer
          format: int32
        activationFunction:
          $ref: '#/components/schemas/TrainingState.ActivationFunctionEnum'
        regularization:
          $ref: '#/components/schemas/TrainingState.RegularizationEnum'
        regularizationRate:
          type: number
          format: float
        trainingType:
          $ref: '#/components/schemas/TrainingState.TrainingTypeEnum'
        trainingLoss:
          type: number
          format: float
        testLoss:
          type: number
          format: float
        numInputs:
          type: integer
          format: int32
        numOutputs:
          type: integer
          format: int32
        numLayers:
          type: integer
          format: int32
        state:
          $ref: '#/components/schemas/TrainingState.TrainingStateEnum'
        currentEpoch:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    TrainingState.ActivationFunctionEnum:
      type: string
      enum:
        - ActivationFunctionIgnore
        - ActivationFunctionNone
        - Relu
        - Sigmoid
        - Tanh
        - Linear
    TrainingState.RegularizationEnum:
      type: string
      enum:
        - RegularizationIgnore
        - L1
        - L2
        - Dropout
        - RegularizationNone
    TrainingState.TrainingStateEnum:
      type: string
      enum:
        - TrainingStateIgnore
        - New
        - Running
        - Error
        - Pause
        - Completed
        - Stopped
    TrainingState.TrainingTypeEnum:
      type: string
      enum:
        - TrainingTypeIgnore
        - Classification
        - Regression
